### ISSUE TITLE
to print "Hello world" in c++

### ISSUE THREAD

**Issue by saurabh-23232** [newridho/Halo-Dunia24#115]
With the help of ASCII values, a unique way to print Hello World! in c++

Assign this issue to me with the label of hacktoberfest

Thank You

**Comment by Taj-2005** [comment]
please assign this task to me for hacktoberfest2024.

**Comment by Taj-2005** [comment]
please add the label hacktoberfest-accepted

**Comment by saurabh-23232** [comment]
> please add the label hacktoberfest-accepted

@newridho +1

**Comment by newridho** [comment]
> please add the label hacktoberfest-accepted
do a pr first
