### ISSUE TITLE
Print "Hello World!" in Bython (Yes, Bython)

### ISSUE THREAD

**Issue by HemanthTenneti** [newridho/Halo-Dunia24#118]
# To Add
- Adding a "Hello World!" program in Bython

### What is Bython?
Bython is Python, but with Brackets. It has the extension ".by" and follows the same syntax as Python except the indentation and colons.

**Comment by newridho** [comment]
okay, do a pr dude
I'll accept it

**Comment by HemanthTenneti** [comment]
Yes, please assign this to me, and I have done a PR aswell. Do review it and lmk.

**Comment by newridho** [comment]
okay done
